# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 95c63a2e50a4cb26e4cf7de3b774ac175dcff1046a6ac3518ddb37bdc4ae3723a4e425801fc8a996b7020845fc3578306fa13ca600e7ab7080bc3b5feba782fa

test:
  domain_name: example.com 
  secret_key_base: 5e5ea939baf959bab480296561584ccbd1e96cfcedc893b4a862c4f7ef22a24f1d6302ee6edc97bba32a995e4c518c92331981894ca3ae160acb9db72b179402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
